"""empty message

Revision ID: bc1af0f4874d
Revises: 4d676c4b73d1
Create Date: 2023-11-17 00:50:30.997384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1af0f4874d'
down_revision = '4d676c4b73d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('mime_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
